---
title: "MOVIE RECOMMENDATION ALGORITHM"
author: "Proyecto creado por Adrián Rico Alonso - 15/12/2021"
output: github_document
---
# RESUMEN
Este proyecto forma parte del último módulo de programa en ciencia de datos de Harvardx. En él se contruye/entrena un modelo de recomendación de películas, es decir, un modelo que sea capaz de predecir la valoración que un determinado usuario otorgará a una determinada película. Se utiliza un conjunto de datos de más de 10 millones de calificaciones otorgadas por más de 70.000 usuarios. 

Una vez el modelo es entrenado (se apuesta por un modelo lineal con regularización) se testea sobre un conjunto totalmente independiente de un millon de calificaciones, consiguiendo un error medio de 0.879 estrellas. Para la entrega del proyecto, se tuvo que realizar un report en inglés que explica con detalle el proceso y el código que se encuentra en el repositorio, puedes encontrarlo en [este post](https://www.linkedin.com/posts/adri%C3%A1n-rico-alonso_report-activity-6876933719308021760-PQ8h)